<?php
/**
 * Created by PhpStorm.
 * User: jonathan
 * Date: 2018/3/9
 */

namespace Koala\Lib\Repository\Criteria;

use Prettus\Repository\Contracts\RepositoryInterface;

class AdvancedSearchCriteria extends BaseCriteria
{


    public $middleware = [

    ];

    public function apply($model, RepositoryInterface $repository)
    {
        return parent::apply($model, $repository); // TODO: Change the autogenerated stub
    }



}